### ISSUE TITLE
serializer DjangoJSONEncoder should be removed

### ISSUE THREAD

**Issue by iksototh** [Frojd/django-react-templatetags#12]
Since django is in version 1.11 now this function is already included, so it should be removed from templatetags

**Comment by marteinn** [comment]
Should be removed after Django 1.10 LTS Expires (https://www.djangoproject.com/weblog/2015/jun/25/roadmap/)

**Comment by marteinn** [comment]
Fixed in 9475bb9b05f49929fcb6e83fc020f0fce6cfa8e4
