### ISSUE TITLE
Support React 15 out of the box?

### ISSUE THREAD

**Issue by rinti** [Frojd/django-react-templatetags#19]
I don't know if it's actually necessary since it's pretty easy to override react_print.html, but ReactDOM.hydrate is only available from React >= 16.

It would be fairly straight forward to support both though. Check if ReactDOM.hydrate is a function, if so use it - else use ReactDOM.render.

Or just mention it in the readme.

**Comment by marteinn** [comment]
Thanks for the ideas :) 

We took a deliberate choice to drop react 15, with the motivation that the react community will move over to 16 pretty quickly. The React 15 support was dropped in November (and was manifested in a major/breaking release). But I think that we missed in communicating the 16+ requirement, so I have added it into the readme.
