### ISSUE TITLE
Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by DaxitaRajput** [Frojd/django-react-templatetags#20]
I got this error(  (index):14 Uncaught ReferenceError: ReactDOM is not defined ) in console while run this code snippet. i am using django 1.11.2. As i am beginner in ReactJS. please help me out.

**Comment by DaxitaRajput** [comment]
Thanks @marteinn But, I have already added ReactJS in my project, since i am getting this error.

**Comment by marteinn** [comment]
@DaxitaRajput Have you also added [react-dom](https://reactjs.org/docs/react-dom.html) to your project?

**Comment by DaxitaRajput** [comment]
yes

**Comment by marteinn** [comment]
@DaxitaRajput And added to the global scope? (Window/Document)

**Comment by marteinn** [comment]
@DaxitaRajput After you import ReactDOM, add it to window. Like this: `window.ReactDOM = ReactDOM` or `window.ReactDOM = require('react-dom');`

**Comment by nnamdiib** [comment]
@marteinn Thanks so much for this lovely library. I think the `ReactDOM` part is not very well specified. I am basically a complete noob in JS frameworks, which specific file should we add the line `window.ReactDOM = ReactDOM` ?

**Comment by marteinn** [comment]
@nnamdiib It depends on your project setup, if you are using webpack you can expose ReactDOM as a external variable: https://github.com/mikaelengstrom/django-react-polls-example/blob/master/frontend/webpack.config.js#L45

You can also add it in your js entrypoint file, see this example that are using Create React App: https://github.com/marteinn/django-react-polls-with-hypernova-examples/blob/master/example_1_with_drtt_hydration/frontend/src/index.js#L13
