### ISSUE TITLE
SSR request content_type not application/json

### ISSUE THREAD

**Issue by aleehedl** [Frojd/django-react-templatetags#23]
Hi,

I'm using this library with a custom Node backend for SSR. As this library sends json to the SSR backend it would be logical to set the `Content-type`  header to `application/json`.  This could be achiewed by setting the header manually like this:
```
headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
requests.post('http://httpbin.org/post', data='{"key": "value"}', headers=headers)
```

or by using the `json` keyword argument provided by requests like this:
```
requests.post('http://httpbin.org/post', json={"key": "value"})
```

**Comment by marteinn** [comment]
Hi @aleehedl! Awesome idea, we have discussed this internally and decided to provide a customizable set of headers, with Content-Type set by default. Will be included in the next release.

**Comment by marteinn** [comment]
Added in 39c8b76b3ca93adcebe27f65ea69bc8498c04330

Setting is `REACT_RENDER_HEADERS`.
Default: `{'Content-type': 'application/json', 'Accept': 'text/plain'}`
