### ISSUE TITLE
render instead of hydrate if SSR turned off

### ISSUE THREAD

**Issue by larsrinn** [Frojd/django-react-templatetags#28]
Hey,

great work, thanks for the package.

I want to use it without SSR. The `ReactDOM.hydrate` call gives me the following warning in the browser console:
```
warning.js:33 Warning: Expected server HTML to contain a matching <div> in <div>.
``` 

While scanning through that issue on a (I guess comparable) rails package, I guessed using `ReactDOM.render` instead will solve the problem: https://github.com/reactjs/react-rails/issues/842

And indeed, it did. I could fix it by overwriting `react_print.html` in my `templates` folder by:
```
<script>
    {% for component in components %}
        ReactDOM.hydrate(
            React.createElement({{ component.name }},
                {% if component.json %}
                    {{ component.json|safe }}
                {% else %}
                    null
                {% endif %}),
            document.getElementById('{{ component.identifier }}')
        );
    {% endfor %}
</script>
```

Would there be a simple way to automatically set it to `ReactDOM.render`, if SSR is not configured? 

Cheers
Lars

**Comment by marteinn** [comment]
There we go: https://github.com/Frojd/django-react-templatetags/commit/48e4713d03f8af69d638c1e36a5330800990a4f5

**Comment by larsrinn** [comment]
It took you 50 minutes from starting to think about it until you had it done with tests and readme updated 😮

**Comment by marteinn** [comment]
@larsrinn Reason = @frojd hackday :)
