### ISSUE TITLE
Individual string props are set to null 

### ISSUE THREAD

**Issue by larsrinn** [Frojd/django-react-templatetags#29]
I think the code speaks for itsself:

If I put this into a template
```
{% react_render component="Component" prop_country="Sweden" prop_city="Stockholm" prop_position=1 %}
{% react_print %}
```

It is rendered like that:
```javascript
ReactDOM.render(
    React.createElement(Component,
        
            {"country": null, "city": null, "position": 1}
        ),
    document.getElementById('Component_5ec708c7a3474dbab0469f7fa02ad3d9')
);
```

**Comment by larsrinn** [comment]
I can fix it quite easily by replacing the `if-else-block` here: https://github.com/Frojd/django-react-templatetags/blob/5697b3976676d9094a6a2e713fbc6e8fabfef3e7/django_react_templatetags/templatetags/react.py#L211 simply by:

```python
value = template.Variable(value)
```

Is there a reason why you explicitly didn't convert individual string props to `template.Variable`? Performance maybe?

**Comment by marteinn** [comment]
This was very straightforward to fix, thanks for the solution! https://github.com/Frojd/django-react-templatetags/commit/87969a4a117bf4af9f65a5863490543a61f989b1
