### ISSUE TITLE
Guidance on inline React component?

### ISSUE THREAD

**Issue by danielmcquillen** [Frojd/django-react-templatetags#30]
Thanks for this really great library. 

The example in the readme shows a "Menu" React component loaded into part of a larger template. But there isn't any guidance on creating this React component for specific use as an inline component in a Django app using `django-react-templates`. 

The example app that is mentioned seems to be a full SPA-like React app built using `react-sass-starterkit`...unsure how that example fits into the inline component approach. 

Do you have any guidance or suggestions for building something more like the "Menu" component? (e.g. create a separate Django app "components" in your project, setup webpack to compile from components/src/my_component.js to static, make sure not to include X, etc. etc.) 

Probably very obvious to most but for a React newbie like me it's hard to discover the easiest way to write an inline (not SPA) React component for use with Django + django-react-templates. 

For example, I'm not sure if using `react-sass-starterkit` is appropriate for an inline component like "Menu"...does it bake in extra js that `django-react-template` will itself provide? Any extra steps to properly integrate the result of a webpack build in `react-sass-starterkit` into the Django app?

Thanks for any suggestions.

**Comment by marteinn** [comment]
Hi @danielmcquillen!

This library was originally built to cover your use case and we have done a couple of larger projects with multiple inlined components.

Here is an example on how a multi-inline approach would look like:

```django
{% load react %}

<div class="HeaderImagePage">
    <div class="HeaderImagePage__Container HeaderImagePage__Container--Video JsHeaderVideo">
        {% react_render component="HeaderVideo" data=header_video_data %}

        <div class="HeaderImagePage__Content">
            <div class="HeaderImagePage__TextContainer">
                <h1 class="HeaderImagePage__Title">{{ page.title }}</h1>
                {% react_render component="PageBuilder" data=page_builder_data %}
                {% block scroll_button %}
                    {% react_render component="ScrollButton" %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
```

The important thing is the run the react_print at the bottom of your base template.

When it comes to the `react-sass-starterkit` integration, it is no requirement. Altough we prefer `react-sass-starterkit`, we have used others in the past, such as `gulp-elixir`. The important thing for these task runners is to export your components so they are available in the global javascript scope and to make sure React and ReactDOM are included. (This library does not include the react js library, we only generate the inline code for it).

Looking at organization we usually have a separate `frontend` dir besides the django application (you can see this in our [Wagtail Boilerplate](https://github.com/Frojd/Wagtail-Boilerplate/tree/master/Client-Project), then we build our assets to a django app named `core`.

Not sure if this answers your questions, but I hope it does :)

**Comment by marteinn** [comment]
I just added a "Multi Component Example" in the readme that might explain things as well: https://github.com/Frojd/django-react-templatetags#multi-component-example

**Comment by danielmcquillen** [comment]
Thanks for the thoughtful answer, @marteinn. I'll have a look at the example you added.

In the meantime, I found something that worked. (Just wanted to keep moving forward w/o worry about build issues yet). I've been including React files directly in my header:
```
<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
 <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
```

And then compiling my test component by running npx in a separate shell to watch the source files I placed (for now) in a separate directly in my top-level Django project:
```
npx babel --watch components/src --out-dir test_project/static/js/components --presets react-app/prod 
```
That has worked well enough just to monkey with the JS and get a better understanding of how things work. But maybe now is the time to look at your examples and think about a better way to build the front-end.

However, I am getting an error in the console:
```
Warning: Expected server HTML to contain a matching <div> in <div>.
```
...but it doesn't seem to prevent the React-based components from working. Strange.

**Comment by marteinn** [comment]
> Can you offer advice on how to use webpack and babel to transform a set of src .js files into something that could be included directly via script tags in my template, such that django-react-templatetags would immediately recognize the components?

We expose components in webpack by using the `expose-loader`.

First we arrange our components like this:

```
/components
  /Button.js
  /Link.js
  index.js
```

In /components/index.js 

import Button from './Button';
import Link from './Link';

export {
    Alert,
}


`require('expose-loader?Components!./components');`

https://raw.githubusercontent.com/Frojd/react-sass-starterkit/2f8e68b01c2d1f6f4241028d08c5d2327d131a2d/app/index.js

**Comment by danielmcquillen** [comment]
Hmm. Using webpack to build an`app.js` seems to imply an SPA. But I'm wondering how you use Webpack to bundle those two React components Button and Link (excluding React and ReactDOM) for separate inclusion into a Django template amonst other template code (not an SPA). But thanks for your help, I realized I've just got more learning to do!

**Comment by danielmcquillen** [comment]
@marteinn would you mind posting your webpack.config.js?

**Comment by marteinn** [comment]
@danielmcquillen Sure! This is the webpack config we normally use (https://github.com/Frojd/Wagtail-Boilerplate/blob/master/Client-Project/frontend/webpack.config.js). Its a part of our [react-sass-starterkit](https://github.com/Frojd/react-sass-starterkit).

I think your config looks fine, glad you got it working! 😄
