### ISSUE TITLE
Create Hypernova plugin to replace Hastur

### ISSUE THREAD

**Issue by niespodd** [Frojd/django-react-templatetags#40]
The Rails community created their equivalent of django-react-templatetags which seems to be much better supported: https://github.com/airbnb/hypernova

Although DRTT works fine - it's fairly simple piece of code - the library provided as SSR backend "Hastur" looks a bit abandoned.

Does anyone use DRTT with Hypernova? Would it be worth integrating it? It looks like they have slightly different API integration on the react bridge.

**Comment by rinti** [comment]
Hi!

It should be possible to replace the provided Hastur SSR-backend through the `REACT_SSR_SERVICE`-setting and plugging in your own.

Hypernova looks super interesting though! It might be worth looking into.

**Comment by marteinn** [comment]
Hi @niespodd 

Hypernova is a interesting piece of technology, I've spent the day setting up a server and building a SSR integration with DRTT and it seems to be working fine, you can find the code for the service here https://github.com/Frojd/django-react-templatetags/blob/develop/django_react_templatetags/ssr/hypernova.py and installation instructions here: https://github.com/Frojd/django-react-templatetags/blob/develop/docs/server-side-rendering.md

I'm also looking into the https://github.com/ornj/hypernova-python (that drives the DRTT service) and will most likely send a couple of pull requests.

**Comment by marteinn** [comment]
This issue has been preceded by https://github.com/Frojd/django-react-templatetags/issues/49
