### ISSUE TITLE
ES modules import

### ISSUE THREAD

**Issue by AriaMoradi** [Frojd/django-react-templatetags#43]
I have been investigating the usage of es module imports for react components in the react template tags in order to not use a bundler in the front end tooling process. Here is where the idea came from: [Building without bundling](https://blog.logrocket.com/building-without-bundling/) and I got a working example that I will post here in the next comment

**Comment by AriaMoradi** [comment]
check out this prototype: [AriaMoradi/django-es-modules-template-tags](https://github.com/AriaMoradi/django-es-modules-template-tags)

**Comment by AriaMoradi** [comment]
To make this work I need to add a few args to the templatetags:
```
{% static 'js/home/components/hello_world.js' as hello_world_path %}
{% react_render component="HelloWorld" use_es_modules=True import_from=hello_world_path  props=None %}
```
and `react_print` should print something like:
```
<script type="module">
        import ReactDOM from "https://unpkg.com/es-react/dev/react-dom.js";

        import HelloWorld from "/static/js/home/components/hello_world.js";

        ReactDOM.render(
            React.createElement(HelloWorld,

                {}
            ),
            document.getElementById('HelloWorld_e1d0f9285e9245ee950929a6edc2d025')
        );
    </script>
```

the first change can be done by setting `REACT_RENDER_TAG_MANAGER` to a custom version of `ReactTagManager`

the latter can not be done, the only way to change this is by changing `django_react_templatetags/templates/react_print.html` so I think the only change needed is to make the template pluggable

**Comment by AriaMoradi** [comment]
ok, I looks like you can override templates too!
just put a template with the same path (here `react_print.html`) in an app and put it above `'django-react-templatetags'` in your `settings.py`!

**Comment by AriaMoradi** [comment]
I will update my prototype app then close this issue

**Comment by AriaMoradi** [comment]
I published a es-modules version of this package for everyone to use.
[django-react-templatetags-es-modules](https://github.com/AriaMoradi/django-react-templatetags-es-modules/)

and example on how to use this package is found in the example project: [django-react-templatetags-es-modules-example](https://github.com/AriaMoradi/django-react-templatetags-es-modules-example/)

**Comment by AriaMoradi** [comment]
How about adding this feature to this project?

**Comment by marteinn** [comment]
Hi @AriaMoradi, I think its a interesting concept and using a custom `react_print.html` is definitely the best way to go when implementing this feature. But I don't see it as a feature of this library, mainly because I do not work with JS this way and would probably maintain it poorly :)

With that said. I think its great that you made a fork along with a example project that can show others how to use ES modules + react in Django!

**Comment by marteinn** [comment]
I'm closing this issue, but lets revise it if things/trends change in the future :)
