### ISSUE TITLE
Support for callbacks/literals

### ISSUE THREAD

**Issue by isolationism** [Frojd/django-react-templatetags#46]
The current approach resolves template variables to a type, or fails. You cannot pass a literal, because the template tag forcibly passes _json_ to the component tag.

This eliminates literally half of the "IO" functionality of React, by killing the "O" part. The only way React components can communicate with the outside world is by _callback_, and this behaviour is unsupported, because functions are not JSON-encodable.

I've looked through the documentation but see only mention of feeding data in, no capability for getting data back out via callback.

Is there something I'm missing, or is there no support for passing in callback functions so that React components can communicate back to the page they're hosted on?

**Comment by marteinn** [comment]
Hi @isolationism, lets see if I understand your question correctly, you want to pass on a python function into the `react_render` templatetag and you want it to run when the react component prop are generated?

We currently do not support callback functions (that in return provide react with data), but adding that as a feature would be a small task which involves overriding our json renderer to run a function when it discovers one.

I'm on the right track with the my question clarification/solution? Otherwise could you provide some sudocode so I know what you try to accomplish? Thank you!

**Comment by isolationism** [comment]
Precisely, @marteinn — If I write something like this:

```
<script type="text/javascript">
  function hello() {
    alert("Hello world!");
  }
  myProps = {
    onEvent: hello
  }
</script>
{% react_render component="Greeting" props=window.myProps %}
```
... It would be great to just be able to pass `window.myProps` through as a literal. Today this fails because of two lines of code:

1. The one you observed in `props_to_json()`: https://github.com/Frojd/django-react-templatetags/blob/develop/django_react_templatetags/templatetags/react.py#L165

2. The `resolve_template_variable_else_none()` method above it, which tries to resolve unquoted values as variables: https://github.com/Frojd/django-react-templatetags/blob/develop/django_react_templatetags/templatetags/react.py#L154

I have made a quick hack in my local copy of your lovely template tag by changing line 169 to read `data = value` and line 179 to simply `return resolved_data` without encoding, and the above code executes fine.

I therefore suggest, as you say, the feature might be expressed as a `raw=True` boolean flag in the template tag, which would pass variables through without attempting to resolve them nor encode to JSON. 

What do you think?

**Comment by niespodd** [comment]
@isolationism I'd resolve this via some uncomplicated HOC looking up callback/`window.` when mounting. Passing `raw` as you proposed could be a security issue when used carelessly.

**Comment by isolationism** [comment]
I guess I'm naïve, but I don't see how it's any different from just writing a tag and two lines of JavaScript myself in a template, which is what I'll do instead. Thanks anyway.

**Comment by WesleyJohnson** [comment]
I know this is closed by the OP, but I have some uses cases for being able to pass JS functions as well. Would be nice if this could be revisited. @isolationism  - What did you send up doing?

**Comment by marteinn** [comment]
@WesleyJohnson I think this issue was resolved by adding needed functions on a global namespace (such as `window`) and retrieving them later from the component by accessing `window`. A short example:

```
<script>
const hello = () => console.log("hello");
window.hello = hello;
</script>
```

```javascript
const MyComp = (props) => {
    const handleClick = (e) => {
        window.hello();
    }

    return (
        <button onClick={handleClick}>Click me</button>
    )
}
```
