### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by mendozao** [Frojd/django-react-templatetags#48]
Hey there,

I was wondering when the next release would be published to pypi? There is useful SSR code currently in the develop branch (added like a month ago) that I don't believe is in v5.4.0 build.

Thank you!

**Comment by marteinn** [comment]
Hi @mendozao! The hypernova support will probably be out in the next couple of weeks, I'm currently working on integrating it into another project https://github.com/Frojd/Wagtail-Pipit/tree/feature/cra, when this implementation is complete (and we have addressed any issues stemming from the integration) we will release it. So stay tuned, I will ping you in this thread once its out. Thanks for showing interest!

**Comment by JustTSK** [comment]
Hey @marteinn! I'm also interested in implementing hypernova in our project.
Any updates on this?

**Comment by marteinn** [comment]
Hi @JustTSK! It's great to see the interest regarding this feature.

So the current state is this:
- We do have support for Hypernova in the develop branch
- And we have a working example here: https://github.com/Frojd/Wagtail-Pipit/tree/feature/cra/Company-Project

What I'm currently researching before doing a official release;
- Hypernova uses another method of initializing client side components. In Django React Templatetags (DRTT) we initialize components by adding component + data in a context processor queue and then iterate the queue in the end and add manual `ReactDOM.hydrate` calls for each. Hypernova has a HOC method called renderReact that digs through the DOM, finds elements and their data and initializes them, so everything is client side without any form of queue, data is stored in the DOM. I'm doing some experimentation in supporting the `renderReact` client side hydration. 
- Hypernova returns its own component wrapper div, which makes us end up with two wrappers, one with DRTT id based div and one with hypernovas `data-hypernova-id`. I'm researching a way to streamline this. It especially effects how the `print_react.html` ends up, right now I need to dig up child node to make sure I hydrate the right div (https://github.com/Frojd/Wagtail-Pipit/blob/feature/cra/Company-Project/src/main/templates/react_print.html#L11).

I hope this explain the current status!

**Comment by JustTSK** [comment]
Thanks @marteinn !  Wagtail-Pipit looks like a nice reference for hypernova implementation, i will definitely take a look.

**Comment by marteinn** [comment]
@JustTSK and @mendozao A quick follow up, I have created a new issue where I track the work we do to finish the Hypernova implementation. You can follow it here: https://github.com/Frojd/django-react-templatetags/issues/49. I'm closing this issue in favour of #49
