### ISSUE TITLE
Removing `react_context_processor` prevents components from being rendered

### ISSUE THREAD

**Issue by retupmoca** [Frojd/django-react-templatetags#54]
Our django application calls `react_render` in various templates to add react components to the page, and then calls `react_print` at the bottom of our main template.

If I remove the `react_context_processor` from our settings.py, as suggested by the deprecation warning, none of our components render. Adding the context processor back in results in them rendering correctly.

I believe this is caused by django's template variable scoping rules: https://docs.djangoproject.com/en/2.2/howto/custom-template-tags/#setting-a-variable-in-the-context
![image](https://user-images.githubusercontent.com/1424544/92254626-b2da3d80-eec0-11ea-848e-8ae7cd53348b.png)

We call `react_render` in a different block than the one that contains the `react_print`, so removing the context processor results in `react_print` not seeing the list of components that was built up by the `react_render` calls.

**Comment by marteinn** [comment]
Thanks for bringing this up @retupmoca! I've seen the issue myself and the proper action here is to make the context processor mandatory again and make sure the docs reflect this.

**Comment by marteinn** [comment]
Resolved in https://github.com/Frojd/django-react-templatetags/releases/tag/v6.0.2
