### ISSUE TITLE
Hypernova SSR Example Doesn't Work

### ISSUE THREAD

**Issue by baranyildirim** [Frojd/django-react-templatetags#58]
I followed the Hypernova SSR example, but the webpages I receive are completely blank.

Tried to run the example directly, the following error occurs on the hypernova server:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
```
Any idea why this could be?

**Comment by marteinn** [comment]
Hi @baranyildirim and thanks for reporting this issue! By looking at the error, it seems like babel register has not been applied, its the bit here https://github.com/marteinn/django-react-polls-with-hypernova-examples/blob/master/example_2_with_builtin_hydration/frontend/hypernova-bootstrap.js#L4 that makes sure hypernova can support ES modules. 

Before I do any research (it takes a little while to get the project running), have you followed the installation guide or done any changes? The installation guide is here: https://github.com/marteinn/django-react-polls-with-hypernova-examples/tree/master/example_2_with_builtin_hydration#installation

**Comment by baranyildirim** [comment]
Hey @marteinn, thanks for responding.

For the example, I followed the installation guide but used yarn because npm was very slow. 

Beyond the example, would it be okay if instead of using the hypernova bootstrapper, I point hypernova directly to babel bundles? This is what I do in my own application, because I want the ability to deploy hypernova easily.

I am pretty sure I have got almost everything right, but my website ends up being blank where the react should be. I know that the Django template is loaded and the SSR is inserted, but get a blank nonetheless.

**Comment by marteinn** [comment]
Thanks for the additional info @baranyildirim, I just set it up locally and also got a ES module error, seems like something has broke since I set up this repo. Doing some research now, will report back when I know more.

**Comment by marteinn** [comment]
Found the culprit, I found the issue while reading through issues for esm (https://github.com/standard-things/esm/issues/868), so it's basically Node introducing a breaking change in v12.16+ and it's an open issue for ESM.

The forward here is either:
- Use an older version of Node, I tested on Node v12.8 and it worked
- Monkey patch the js module loader with something like this (https://github.com/standard-things/esm/issues/855#issuecomment-566825957 or https://github.com/standard-things/esm/issues/868#issuecomment-594480715), I have not tested it so cannot verify that it works.

My immediate action will be to pin the node version for this repo, at the moment I don't have time to find a more sustainable solution, but PR:s are of course much welcome!

**Comment by marteinn** [comment]
Just pushed out a quickfix: https://github.com/marteinn/django-react-polls-with-hypernova-examples/commit/61dca485f77266bcf84ed4774200e957c5e0b615

I'm also planning on closing this issue (will keep it open a couple of hours more for discussions) and instead open up a new issue at the https://github.com/marteinn/django-react-polls-with-hypernova-examples repo, as it is not a DRTT issue with rather in one of the examples. DRTT has no opinion on how you do implement your hypernova server.

**Comment by marteinn** [comment]
And here is the issue I opened on the other repo: https://github.com/marteinn/django-react-polls-with-hypernova-examples/issues/1 (I noticed that issues was deactivated for the repo, so I activated those as well).

**Comment by baranyildirim** [comment]
Tried the example again and it works with Node 12.13.0
