### ISSUE TITLE
Some tests misusing assertTrue for comparisons

### ISSUE THREAD

**Issue by code-review-doctor** [Frojd/django-react-templatetags#63]
`assertTrue` is not for comparing arguments, should use `assertEqual` for that.

The developer's intent of the test was to compare argument 1 with argument 2, which is not happening. Really what is happening is the test is passing because first argument is truthy. The correct method to use is assertEqual. [more details](https://codereview.doctor/features/python/best-practice/avoid-misusing-unittest-assert-true)

https://github.com/Frojd/django-react-templatetags/blob/cb781d6eaa7b19b49840543ee22f7bd243d97dec/django_react_templatetags/tests/test_ssr_hypernova_service.py#L205

I found this issue automatically, see other issues [here](https://codereview.doctor/Frojd/django-react-templatetags)

**Comment by marteinn** [comment]
Fixed in https://github.com/Frojd/django-react-templatetags/commit/bd810b971c1a7d6caa7fb747d9aad42e9cc19a38
