### ISSUE TITLE
Uncaught ReferenceError: Component is not defined

### ISSUE THREAD

**Issue by tay-solis** [Frojd/django-react-templatetags#65]
Hello!

Thank you for this fantastic library. I'm working on implementing it for a new project, and I'm running into an issue in the initial set up.

I've got the React and ReactDOM global imports working, but the script tag is throwing `Uncaught ReferenceError: KnowledgeBase is not defined`. I've looked through both examples but I can't figure out what I'm doing wrong.

How can I get this component accessible to the template? Am I exporting my components incorrectly?

Here's the code I'm using. We're building using webpack as well:

### knowledge_base.html
```
{% block main %}
<noscript>You need to enable JavaScript to run this app.</noscript>

{% react_render component="KnowledgeBase" props=kb_home_data identifier="knowledgebase" %}

{% endblock main %}

{% block extra_js %}
    <script type="text/javascript" src="{{ WEBPACK_TEMPLATES_BUNDLE }}"></script>
    <script type="text/javascript" src="{{ WEBPACK_KB_BUNDLE }}"></script>
    {% react_print %}
{% endblock %}
```

### knowledgebase/index.js
```
import KnowledgeBase from './KnowledgeBase';

export default {
  KnowledgeBase
}
```

### knowledgebase/KnowledgeBase.js
```
import React, {Component} from "react";

export default class KnowledgeBase extends Component {
  constructor(props) {
    super(props);
  }

  render(){
    console.log(this.props);
    return <h1>KnowledgeBase</h1>;
  }

}
```

Thank you so much!

**Comment by tay-solis** [comment]
I got it running by adding `window.KnowledgeBase = KnowledgeBase;` to the index.js file. Is this how I'm supposed to do it?

**Comment by marteinn** [comment]
Hi @tay-solis! 

That is correct, you need to expose your component so they can be referenced to in the rendering process. You can either do it just like you did, by making the component a global variable or adding it to a object that we later expose (here is an example in webpack https://github.com/mikaelengstrom/django-react-polls-example/blob/master/frontend/app/index.js).

For bigger apps I would go with second approach and just expose a big object called Components or Containers and then reference it in the render by using the `REACT_COMPONENT_PREFIX` setting (read more here https://github.com/Frojd/django-react-templatetags/blob/develop/docs/settings.md).

We also have two examples, they can be found here: https://github.com/Frojd/django-react-templatetags/blob/develop/docs/examples.md, both use this approach.

Hope this helps!
